config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :collaborators, only: [:new,:destroy, :create]

  resources :charges, only: [:new, :create]

  resources :wikis

  post '/downgrading' => 'account#downgrading'

  get 'account' => 'account#index'

  get 'downgrade' => 'account#downgrade'

  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy

  #order is handled in controller
  #default_scope { order(created_at: :desc) }

  #trying to add option to change order of scope
  #scope :ordered_by_title, -> { order(title: :asc) }
  #scope :ordered_by_reverse_created_at, -> { reorder(created_at: :ASC)}
  #scope :user_order, lambda { order("#{current_user.order_column} #{current_user.order_direction}")}


end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  after_action :verify_authorized
  before_action :authenticate_user!
  def index
    # here we define the order of the list before its rendered, with the methods `sort column` and `sort_direction` defined in private below
    #@wikis = Wiki.order("LOWER("+ sort_column + ") " + sort_direction)
    @wikis = policy_scope(Wiki.order(sort_column + " " + sort_direction))
    authorize Wiki
  end

  def create
    #wiki_params private method below
    @wiki_page = Wiki.new(wiki_params)
    @wiki_page.user = current_user
    authorize @wiki_page
    if @wiki_page.save
      flash[:notice] = "Post was saved."
      redirect_to @wiki_page
    else
      flash.now[:alert] = "There was an error saving. Please try again"
      render :new
    end
  end

  def new
    @wiki_page = Wiki.new
    authorize Wiki
  end

  def edit
    @wiki_page = Wiki.find(params[:id])
    #@collaborators = @wiki_page.collaborators
    authorize @wiki_page
  end

  def update
    @wiki_page = Wiki.find(params[:id])
    @wiki_page.assign_attributes(wiki_params)
    authorize @wiki_page
    if @wiki_page.save
      flash[:notice] = "Post was updated."
      redirect_to [@wiki_page]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
    end
  end

  def show
    @wiki_page = Wiki.find(params[:id])
    authorize @wiki_page
  end

  def destroy
    @wiki_page = Wiki.find(params[:id])
    authorize @wiki_page
    if @wiki_page.destroy
      flash[:notice] = "\"#{@wiki_page.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  #method that white lists (allows privilege for) the parameters we need to create comments.
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end


  # sort_column returns a value to to the index action
  #checks columns of a Wiki, if included pass param, else default
  def sort_column
    Wiki.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  # %w creates array of strings
  # same as above
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/wikis/_collaborators.html.erb
<%= form_for Collaborator.new do |f| %>
  <dif class="form-group">
    <%= f.text_field :id %>
    <%= f.hidden_field :wiki_id, value: @wiki_page.id %><br>
  <div class="form-group">
    <%= f.submit "Add", class: 'btn btn-success'  %>
  </div>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  </div>
  <% if current_user.admin? || current_user.premium? # dont need this because a user shouldn't able to edit someone elses wiki without being a collaborator && current_user.id == wiki.user_id %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <!-- <dif class="form-group">
    <% f.label :collaborators %>
    <% f.text_field :collaborators, class: 'form-control', placeholder: "email seperated by space example: sample@mail.com AnotherSample@mail.com third@mail.com" %> -->
  <!-- form to add collaborators here with example of how to do it. find user by email. add the id number to collaborator push email to wiki.collaborator if email exists in users -->
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/wikis/_form_collaborators.html.erb
<%= form_for Collaborator.new do |f| %>
  <dif class="form-group">
    <%= f.text_field :id %>
    <%= f.hidden_field :wiki_id, value: @wiki_page.id %><br>
  </div>
  <div class="form-group">
    <%= f.submit "Add", class: 'btn btn-success'  %>
  </div>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki %>
      <small> <%=  index_markdown(wiki.body) %> </small>
    </h4>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1> edit </h1>

<div class="row">
  <div class="col-md-4">
    <p> Making a revision</p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki_page} %>
  </div>
</div>

<div class="col-md-8">
  <h4> Collaborators </h4>
  <%= render @wiki_page.collaborators %>
  <%= render partial: 'form_collaborators' %>
</div>

app/views/wikis/index.html.erb
<h1> Wikiz </h1>



<div class="col-md-8">
  <div class='sort'>
    <div class='sort'>

      <!-- reads link_to <arbitrary name>, <route_path>(params: {<hash key>: <value goes to controller>}), class: <bootstrap default classes>    -->
      <%= link_to 'default/newest', wikis_path(params: {sort: 'created_at', direction: 'desc'}) ,class:'btn-default btn-xs' %>
      <%= link_to 'A-Z', wikis_path(params: {sort: 'title', direction: 'asc'}) ,class: 'btn-default btn-xs' %>
      <%= link_to 'Z-A', wikis_path(params: {sort: 'title', direction: 'desc'}) ,class:'btn-default btn-xs' %>
      <%= link_to 'oldest', wikis_path(params: {sort: 'created_at', direction: 'asc'}) ,class:'btn-default btn-xs' %>

  </div>
  </div>
    <%= render @wikis %>
</div>

<div class="col-md-4">
  <%= link_to "New Wiki", new_wiki_path(params: {user: current_user}), class: 'btn btn-success' %>
</div>

app/views/wikis/new.html.erb
<h1> new </h1>
<div class="row">
  <div class="col-md-4">
    <p> creating a wiki page </p>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki_page} %>
  </div>
</div>

app/views/wikis/show.html.erb
<div>
  <h1> <%= @wiki_page.title %> </h1>
  <p> <%= markdown(@wiki_page.body) %> </p>
  <small> Created at <%= time_ago_in_words(@wiki_page.created_at) %> </small>
</div>
  <%= link_to "Edit", edit_wiki_path(@wiki_page), class: 'btn btn-success' %>
  <%= link_to "Delete Topic", @wiki_page, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>